id: page_${page_index}
lambda: |-
  it.image(${image_x},${image_y}, id(${image}), id(colors)[${page_index}], Color::BLACK);
  auto t = id(notification_received)[${page_index}];
  if (t > 0) {
    auto o_time = ESPTime::from_epoch_local(t);
    it.strftime(${text_x},${text_y}, id(roboto_32), "um %H:%M", o_time);
  }